
# Configuration file for the zipper tool
# Normally located in the installation folder 

[files]
mdr_zipped="E:\\MDR\\Zipped source files"
mdr_unzipped="E:\\MDR\\MDR Source files"

fdr_zipped="E:\\MDR source data\\UMLS\\zipped data"
fdr_unzipped="E:\\MDR source data\\UMLS\\data"

log_folder_path="E:\\MDR\\Zipping\\logs"

[database]
db_host="localhost"
db_user="postgres"
db_password="WinterIsComing!"
db_port="5433"
